glucologweb:
  username: <glucologweb username/email>
  password: <glucologweb Password>
  timeZoneOffset: UTC
  loginURL: https://www.glucologweb.com/login-tz
  dataURL: https://www.glucologweb.com/cgm/getDayGraphData/
  units: mmol/l #mg/dl

nightscout:
  URL: <nightScout URL>  # without trailing slash "/" ex. https://xxx.herokuapp.com
  token: <nightScout Token> 

general:
  numOfReadingToSync: 60  #increasing this number will make the app use more cumputing time & networking and may increase costs
  logLevel: 5  # 0 for no logs, 10 for all logs, 5 for default log level
