glucologweb:
  username: <glucologweb username/email>
  password: <glucologweb Rotem>
  timeZoneOffset: UTC
  loginURL: https://www.glucologweb.com/login-tz
  dataURL: https://www.glucologweb.com/cgm/getDayGraphData/
  units: mmol/l #mg/dl

nightScout:
  URL: <nightScout URL>
  token: <nightScout Token>